# Generated by Django 4.1.2 on 2022-12-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Назва Компанії'),
        ),
    ]
