# Generated by Django 4.1.2 on 2022-12-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_alter_joblist_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Назва компанії'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='job_description',
            field=models.TextField(verbose_name='Детальніше про вакансію статьи'),
        ),
    ]
