# Generated by Django 4.1.2 on 2022-12-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_alter_company_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=110, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='job_description',
            field=models.TextField(verbose_name='Детальніше про вакансію'),
        ),
    ]
