# Generated by Django 4.1.2 on 2022-12-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_alter_category_slug_alter_joblist_job_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
    ]
